In [18]:
%run -n speeach_recognizer.py -i data
import numpy as np
import warnings
import os
from scipy.io import wavfile
from python_speech_features import mfcc
from speeach_recognizer import HMMTrainer


In [19]:
input_folder = 'C:/Users/carlc/Downloads/speech_recognition_hmm-master/speech_recognition_hmm-master/data'
X = np.array([])
y = []
hmm_models = [] 
warnings.filterwarnings('ignore')

for dirname in os.listdir(input_folder):
    subfolder = os.path.join(input_folder, dirname)

    if not os.path.isdir(subfolder):
        continue

    label = subfolder[subfolder.rfind('/') + 1:]
    for filename in [x for x in os.listdir(subfolder) if x.endswith('.wav')][:-1]:
        filepath = os.path.join(subfolder, filename)
        sampling_freq, audio = wavfile.read(filepath)

        mfcc_features = mfcc(audio, sampling_freq)
        if len(X) == 0:
            X = mfcc_features
        else:
            X = np.append(X, mfcc_features, axis=0)
        y.append(label)

    # Each model builds for each class
    hmm_trainer = HMMTrainer()
    print('Train', label, 'X shape', X.shape)
    hmm_trainer.train(X)
    hmm_models.append((hmm_trainer, label))
    hmm_trainer = None

Train data\apple X shape (558, 13)
Train data\banana X shape (1262, 13)
Train data\kiwi X shape (1811, 13)
Train data\lime X shape (2413, 13)
Train data\orange X shape (3488, 13)
Train data\peach X shape (4398, 13)
Train data\pineapple X shape (5195, 13)


In [20]:
for trainer, label in hmm_models:
    print("label", label)
    print("============")
    model = trainer.model
    print("Transition matrix")
    print(model.transmat_)

    print("Means and vars of each hidden state")
    for i in range(model.n_components):
        print("{0}th hidden state".format(i))
        print("mean = ", model.means_[i])
        print("var = ", np.diag(model.covars_[i]))

label data\apple
Transition matrix
[[7.74632870e-001 9.38288065e-002 3.07276906e-002 1.00810633e-001]
 [3.18942971e-002 8.98387569e-001 6.97181340e-002 1.52181649e-090]
 [1.09853168e-001 2.65649918e-008 8.90146805e-001 6.52623362e-051]
 [9.36873852e-002 5.62240110e-126 1.70991436e-117 9.06312615e-001]]
Means and vars of each hidden state
0th hidden state
mean =  [ 15.70619212  -4.95909195 -22.03589871 -17.14789391 -21.26591767
  -4.49458836  -1.54800854   2.10307483  -4.5630265    6.62050479
  -1.07548114 -11.97153496  -8.373853  ]
var =  [  3.35783416  73.00218187  46.8069547  101.7956628   97.69828637
  77.84896302  87.35436888  96.56018149  69.02116962  75.68839401
  59.6364865   72.52411518  62.0488845 ]
1th hidden state
mean =  [ 19.64871636 -16.67793101 -34.99976213  -1.68595529 -13.65600609
  13.19572562  -7.83841234   3.59877481 -17.77749721  13.43542514
   9.07171046 -20.94046163  -0.33561945]
var =  [  2.40889508  44.41842103  54.11696091  61.40021817  84.8857971
 138.8846220